// swift-tools-version: 6.3

// © 2018–2026 John Gary Pusey (see LICENSE.md)

import PackageDescription

let swiftSettings: [SwiftSetting] = [.defaultIsolation(nil),
                                     .enableUpcomingFeature("ExistentialAny"),
                                     .enableUpcomingFeature("ImmutableWeakCaptures"),
                                     .enableUpcomingFeature("InferIsolatedConformances"),
                                     .enableUpcomingFeature("InternalImportsByDefault"),
                                     .enableUpcomingFeature("MemberImportVisibility"),
                                     .enableUpcomingFeature("NonisolatedNonsendingByDefault")]

let package = Package(name: "XestiTools",
                      platforms: [.iOS(.v16),
                                  .macOS(.v14)],
                      products: [.library(name: "XestiTools",
                                          targets: ["XestiTools"]),
                                 .library(name: "XestiToolsCLI",
                                          targets: ["XestiToolsCLI"]),
                                 .library(name: "XestiToolsZIP",
                                          targets: ["XestiToolsZIP"])],
                      dependencies: [.package(url: "https://github.com/apple/swift-argument-parser.git",
                                              .upToNextMajor(from: "1.8.0")),
                                     .package(url: "https://github.com/weichsel/ZIPFoundation.git",
                                              .upToNextMajor(from: "0.9.0"))],
                      targets: [.target(name: "XestiTools",
                                        swiftSettings: swiftSettings),
                                .target(name: "XestiToolsCLI",
                                        dependencies: [.target(name: "XestiTools"),
                                                       .product(name: "ArgumentParser",
                                                                package: "swift-argument-parser")],
                                        swiftSettings: swiftSettings),
                                .target(name: "XestiToolsZIP",
                                        dependencies: [.target(name: "XestiTools"),
                                                       .product(name: "ZIPFoundation",
                                                                package: "ZIPFoundation")],
                                        swiftSettings: swiftSettings),
                                .testTarget(name: "XestiToolsTests",
                                            dependencies: [.target(name: "XestiTools")],
                                            swiftSettings: swiftSettings),
                                .testTarget(name: "XestiToolsCLITests",
                                            dependencies: [.target(name: "XestiTools"),
                                                           .target(name: "XestiToolsCLI")],
                                            swiftSettings: swiftSettings),
                                .testTarget(name: "XestiToolsZIPTests",
                                            dependencies: [.target(name: "XestiTools"),
                                                           .target(name: "XestiToolsZIP")],
                                            swiftSettings: swiftSettings)],
                      swiftLanguageModes: [.v6])
